### ISSUE TITLE
add opalrb.org

### ISSUE THREAD

**Issue by zaxebo1** [cogitator/ruby-implementations#1]
opal ( http://www.opalrb.org ) converts ruby source code to javascript source code . It is used in production and full feature complete.

**Comment by codicoscepticos** [comment]
**Opal** is already in the list, as: "[**Opal**](http://opalrb.org/) : Opal is a ruby to _javascript_ compiler."

Though, I've just changed the text to: "[**Opal**](http://opalrb.org/) : Opal is a ruby to _javascript_ source-to-source compiler."
